In [2]:
import sys

In [3]:
print(sys.version) #system version

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


In [4]:
import platform
platform.python_version() #python python_version

'3.8.5'

In [6]:
#types
i = 3
type(i)

int

In [10]:
5/2

2.5

In [12]:
5//2

2

In [48]:
int(5.2)

5

## Creating arrays

In [2]:
#import numpy library
import numpy as np

In [3]:
#numpy array
f_array = np.array([1,2,3,4])

In [4]:
print(f_array)

[1 2 3 4]


In [5]:
#array with zeros
array_z = np.zeros((3,3))
array_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#array with ones
array_o = np.ones((3,3))
array_o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#array with empty - fills with random numbers
array_e = np.empty((2,3))
array_e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#array with arange - from zero to length(excluding)- only 1D
np_arrange = np.arange(12)
np_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
#reshape to 2D
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
#linspace for linearly equal spaced data elements
np_linspace= np.linspace(1,6,3)
np_linspace

array([1. , 3.5, 6. ])

In [28]:
#create 3D
oneD_array = np.arange(15)
threeD_array = oneD_array.reshape(1,3,5)
threeD_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [29]:
#create a 3d array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
#get dimentsion, axis or rank of ran array
threeD_array.ndim

3

In [36]:
#indicates the siz in each dimension as tuple
oneD_array.shape

(15,)

In [37]:
array_e.shape

(2, 3)

In [38]:
threeD_array.shape

(3, 3, 3)

In [40]:
#number elements in a array
oneD_array.size

15

In [42]:
threeD_array.size

27

In [50]:
#type of elements in an array
threeD_array.dtype

dtype('int32')

## Arithmatic operations on arrays
### Element wise operation

In [52]:
array_add = np.array([1,2])+np.array([1,4])
array_add

array([2, 6])

In [54]:
array_a = np.array([1,2])
array_b = np.array([3,4])
np.add(45,20)

65

In [56]:
np.subtract(20,45)

-25

In [58]:
array_a = array_a*15
array_a

array([225, 450])

In [60]:
#sum elements in a array in last dimension
sum(threeD_array)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

### Comparison operartion

In [47]:
new_array = np.array([1, 3], dtype = float)
new_array.dtype

dtype('float64')